#!/bin/bash

# clean build folder
./clean

# copy files into build folder
for D in src/*; do
    if [ -d "${D}" ]; then
        function_name=$(basename "${D}")
        echo "Copying ${function_name} to build/" 
        cp -r "${D}/" "build/${function_name}" > /dev/null 2>&1
    fi
done
for D in tst/*; do
    if [ -d "${D}" ]; then
        function_name=$(basename "${D}")
        echo "copying ${function_name} tests" 
        cp -r "${D}"/* "build/${function_name}" > /dev/null 2>&1
    fi
done

### Test ###

echo "executing tests"
cd build || exit
coverage run --rcfile='../.coveragerc' -m pytest --disable-socket || { echo "tests failed, exiting" ; exit 1; }
coverage html
coverage report --rcfile='../.coveragerc' || exit 1
cd .. || exit