#!/bin/bash

# clean build folder
./clean

# copy files into build folder
for D in src/lambda/*; do
    if [ -d "${D}" ]; then
        function_name=$(basename "${D}")
        echo "Copying ${function_name} to build/" 
        cp -r "${D}/" "build/${function_name}"
    fi
done
for D in tst/lambda/*; do
    if [ -d "${D}" ]; then
        function_name=$(basename "${D}")
        echo "copying ${function_name} tests" 
        cp -r "${D}"/* "build/${function_name}"
    fi
done

### Test ###

echo "executing tests"
cd build || exit
coverage run --rcfile='../.coveragerc' -m pytest || { echo "tests failed, exiting" ; exit 1; }
coverage html
coverage report --rcfile='../.coveragerc' || exit 1
cd .. || exit